In [1]:
from typing import List, Optional
from datetime import date
import pandas as pd
import yfinance as yf

In [2]:
import requests
PROXIES = {
   'http': 'socks5://127.0.0.1:1082',
   'https': 'socks5://127.0.0.1:1082',
}
session = requests.Session()
session.proxies = PROXIES

# yfinance
- [PyPI](https://pypi.org/project/yfinance/)

In [3]:
aapl = yf.Ticker("AAPL", session=session)
# aapl.info
# aapl.financials
# aapl.quarterly_financials
hist = aapl.history(period="1y", actions=False)
hist.head()

,Open,High,Low,Close,Volume
Date,,,,,
2021-10-22 00:00:00-04:00,148.855893,149.343153,147.811741,147.861465,58883400
2021-10-25 00:00:00-04:00,147.851492,148.537650,146.797401,147.811722,50720600
2021-10-26 00:00:00-04:00,148.497884,149.999465,148.179660,148.487946,60893400
2021-10-27 00:00:00-04:00,148.527722,148.895655,147.662574,148.020569,56094900
2021-10-28 00:00:00-04:00,148.985172,152.316496,148.885723,151.719849,100077900

In [ ]:
tickers = yf.Tickers('MSFT AAPL GOOG', session=session)
hist = tickers.history(period="max", actions=False)
hist.head()

# API

In [12]:
def get_stock_data(symbol: List[str], start: Optional[str]=None, 
                   end: Optional[str]=None, period: str="2y", 
                   interval: str="1d", session: Optional[requests.Session]=None):
    if end is None:
        end = date.today().strftime('%Y-%m-%d')
    ticker = yf.Ticker(symbol, session=session)
    data = ticker.history(start=start, end=end, interval=interval, period=period, actions=False)
    data.reset_index(inplace=True)
    data.rename(columns={
        "Date": "date",
        "Open": "open",
        "Low": "low",
        "Close": "close",
        "Adj Close": "adj_close",
        "Volume": "volume"
    }, inplace=True)
    data['symbol'] = symbol
    return data

In [13]:
stock_data = get_stock_data("AAPL", start="2022-01-01", session=session)
stock_data.head()

,date,open,High,low,close,volume,symbol
0,2022-01-03 00:00:00-05:00,177.097152,182.126343,176.977651,181.259918,104487900,AAPL
1,2022-01-04 00:00:00-05:00,181.877375,182.186095,178.381831,178.959442,99310400,AAPL
2,2022-01-05 00:00:00-05:00,178.869833,179.427523,173.920313,174.199158,94537600,AAPL
3,2022-01-06 00:00:00-05:00,171.988296,174.577587,170.932666,171.291183,96904000,AAPL
4,2022-01-07 00:00:00-05:00,172.177529,173.422378,170.325193,171.460495,86709100,AAPL